version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
    - "6379:6379"
    command: ["redis-server", "--requirepass", "password123"]
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
    - "5540:5540"
    volumes:
    - redis-insight:/data

volumes:
   redis-insight: